package com.studioflow.enums;

public enum AuditEntityType {
    APPOINTMENT,
    PAYMENT,
    CLIENT,
    STAFF,
    SERVICE,
    PACKAGE,
    CLIENT_PACKAGE,
    INVENTORY_PRODUCT,
    WAITLIST_ENTRY,
    WAITLIST_OFFER,
    CONSENT_TEMPLATE,
    CONSENT_SUBMISSION,
    LOCATION,
    SETTINGS,
    AUTH,
    ONBOARDING
}
