package com.studioflow.enums;

public enum NotificationType {
    APPOINTMENT_CREATED,
    APPOINTMENT_RESCHEDULED,
    APPOINTMENT_CANCELLED,
    APPOINTMENT_REMINDER,
    PAYMENT_RECORDED,
    PAYMENT_PENDING,
    CONSENT_PENDING,
    CONSENT_SIGNED
}
